name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # 将代码拷贝到虚机中

    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@releases/v3 
      env:
        ACCESS_TOKEN: ${{ secrets.MY_VUE_PROJECT_TOKEN }} # 使用刚新建的secret
        BRANCH: gh-pages # 存放产物的分支名称
        FOLDER: dist # 存放build后产物的目录
        BUILD_SCRIPT: npm install && npm run build # 执行的命令
